namespace MojoShaderDotNet.Types;

/// <summary>
/// Structure used to return data from parsing of a shader...
/// </summary>
public class MojoShaderCompileData
{
    /// <summary>
    /// Elements of data that specify errors that were generated
    ///  by compiling this shader.
    /// </summary>
    public List<MojoShaderError> Errors { get; set; } = new();

    /// <summary>
    /// Elements of data that specify errors that were
    ///  generated by compiling this shader.
    /// </summary>
    public List<MojoShaderError> Warnings { get; set; } = new();

    /// <summary>
    /// The name of the source profile used to compile the shader. Will be NULL
    ///  on error.
    /// </summary>
    public string? SourceProfile { get; set; }

    /// <summary>
    /// Bytes of output from compiling. This will be a
    ///  string of D3D assembly source code.
    /// </summary>
    public string? Output { get; set; }

    /// <summary>
    /// Elements of data that specify high-level symbol data
    ///  for the shader. This can be used by MOJOSHADER_assemble() to
    ///  generate a CTAB section in bytecode, which is needed by
    ///  MOJOSHADER_parseData() to handle some shaders.
    /// </summary>
    public List<MojoShaderSymbol> Symbols { get; set; } = new();
}